### ISSUE TITLE
Stoped working in Slack 4.0

### ISSUE THREAD

**Issue by bauerp** [mykeels/slack-theme-cli#33]
Apparently Slack made some changes which doesn't allow this to work anymore. Hope that you can fix this.

**Comment by xxKeith20xx** [comment]
I get the following:

```
~/ sudo slack-theme night
file does not exist

```

**Comment by OkBeacon** [comment]
Please check https://github.com/mykeels/slack-theme-cli/issues/32#issuecomment-511490655 

Following worked for me-
```
$ sudo slack-theme uninstall
$ curl https://raw.githubusercontent.com/mykeels/slack-theme-cli/master/slack-theme -O && SLACK_THEME_SHELL_PROFILE=~/.zshrc bash slack-theme install && . ~/.zshrc
$ slack-theme night
$ slack-theme midnight-blue
```

Would you please check ?

**Comment by xxKeith20xx** [comment]
@OkBeacon I just tried it w/ zsh and it seems to run, but still shows the default slack theme for me?

**Comment by mykeels** [comment]
@OkBeacon, I'm glad it works for you.

@xxKeith20xx, are you saying no matter what slack-theme command you run, only the default white theme shows?

**Comment by xxKeith20xx** [comment]
I tried again and now slack fails to open with this error:

```
A JavaScript error occurred in the main process:
Uncaught Exception:
Error: Unable to find a valid app
    at Object.<anonymous> (/Applications/Slack.app/Contents/Resources/electron.asar/browser/init.js:120:9)
    at Object.<anonymous> (/Applications/Slack.app/Contents/Resources/electron.asar/browser/init.js:190:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules
```/cjs/loader.js:533:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:746:12)
    at startup (internal/bootstrap/node.js:282:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:759:3)

**Comment by guhanrv** [comment]
I get "no matching processes belonging to you were found" and it opens up normally.

**Comment by bauerp** [comment]
I got it to work using OkBeacon's method. Thanks!

**Comment by ransagy** [comment]
Anyone managed to get it working in Windows/WSL? Just can't seem to get it to run properly.

**Comment by bauerp** [comment]
Although OkBeacon's method worked on my on Macbook, it doesn't work for my iMac for some reason :/

**Comment by mykeels** [comment]
@ransagy I hope to spend sometime this weekend getting it working for Windows

**Comment by kevcenteno** [comment]
This is broken on linux as well.

**Comment by kishorramanan** [comment]
tried steps by @OkBeacon still loading with default white

**Comment by bauerp** [comment]
Using OkBeacon's method works for me initially, but after a day or two it automatically reverts back to the default theme while still being on the same Slack version. This is happening on both my Macs.

**Comment by kkuhle** [comment]
+1 on WSL

**Comment by dubhunter** [comment]
Bump

**Comment by adeebahmed** [comment]
> Using OkBeacon's method works for me initially, but after a day or two it automatically reverts back to the default theme while still being on the same Slack version. This is happening on both my Macs.

My experience has been the same

**Comment by gitjonez** [comment]
I installed for the first time. No themes worked.
Tried: `slack-theme uninstall`: the running Slack quit.
Starting it back up: 
*A JavaScript error occurred in the main process*
```Uncaught Exception:
Error: Unable to find a valid app
    at Object.<anonymous> (/Applications/Slack.app/Contents/Resources/electron.asar/browser/init.js:120:9)
    at Object.<anonymous> (/Applications/Slack.app/Contents/Resources/electron.asar/browser/init.js:190:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:746:12)
    at startup (internal/bootstrap/node.js:282:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:759:3)
```
The file: `Applications/Slack.app/Contents/Resources/electron.asar/browser/init.js` doesn't exist: `electron.asar` is a file, not a directory.

**Comment by luisdavim** [comment]
this worked for me: https://github.com/widget-/slack-black-theme/issues/98#issuecomment-511449693
